# Generated by Django 6.0.3 on 2026-04-29 09:57

import core.model_normalization
import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_start', models.TimeField(default='08:00:00')),
                ('work_end', models.TimeField(default='15:00:00')),
                ('max_tolerance', models.DurationField(default='00:15:00')),
                ('auto_close_hours', models.IntegerField(default=12)),
                ('weekend_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list)),
                ('holidays', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'company_settings',
                'managed': False,
            },
            bases=(core.model_normalization.UppercaseNormalizationMixin, models.Model),
        ),
    ]
