# Generated by Django 6.0.3 on 2026-03-18 12:34

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_start', models.TimeField(default='08:00:00')),
                ('work_end', models.TimeField(default='15:00:00')),
                ('max_tolerance', models.DurationField(default='00:15:00')),
                ('auto_close_hours', models.IntegerField(default=12)),
                ('weekend_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list)),
                ('holidays', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'company_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCompanyMembership',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_company_membership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('password_hash', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
