# Generated by Django 6.0.3 on 2026-03-18 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequests',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('correction_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'correction_requests',
                'managed': False,
            },
        ),
    ]
