# Generated by Django 6.0.3 on 2026-03-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_correctionrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionrequests',
            options={},
        ),
    ]
