# Generated by Django 6.0.3 on 2026-03-24 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
        ('users', '0005_alter_correctionrequests_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionrequests',
            name='approver',
            field=models.ForeignKey(blank=True, db_column='approver_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correctionrequests_approver_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionrequests',
            name='new_clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctionrequests',
            name='new_clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctionrequests',
            name='requester',
            field=models.ForeignKey(blank=True, db_column='requester_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionrequests',
            name='time_entry',
            field=models.ForeignKey(blank=True, db_column='time_entry_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracking.timeentries'),
        ),
    ]
