# Generated by Django 6.0.3 on 2026-03-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_correctionrequests_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionrequests',
            options={'managed': False},
        ),
    ]
