# Generated by Django 6.0.3 on 2026-05-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_correctionrequests_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySettings',
        ),
        migrations.DeleteModel(
            name='CorrectionRequests',
        ),
        migrations.AlterModelTable(
            name='usercompany',
            table='user_company',
        ),
    ]
