# Generated by Django 6.0.3 on 2026-03-18 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.UUIDField()),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('voided', 'Voided'), ('manual_correction', 'Manual Correction')], max_length=20)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
    ]
