# ---------- Backend Forms: users/forms.py ----------

import secrets
import string

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from users.models import Users, Companies, UserCompany


# ── Helper: temporary password generator ──────────────────────────────────

def generate_temp_password(length=12):
    """Generate a secure random temporary password."""
    upper     = string.ascii_uppercase
    lower     = string.ascii_lowercase
    digits    = string.digits
    special   = '!@#$%&*?'
    all_chars = upper + lower + digits + special

    # Ensure at least one character of each type
    password = [
        secrets.choice(upper),
        secrets.choice(lower),
        secrets.choice(digits),
        secrets.choice(special),
    ]
    password += [secrets.choice(all_chars) for _ in range(length - 4)]
    secrets.SystemRandom().shuffle(password)
    return ''.join(password)


# ── Base user form ───────────────────────────────────────────────────────

class _UserBaseForm(forms.ModelForm):
    """
    Reusable base for all user forms.

    KEY CHANGE: the 'password' widget is TextInput (not PasswordInput).
    PasswordInput has render_value=False by default, which makes Django
    discard the value in POST so it arrives empty in cleaned_data. Since the
    temporary password is visible in the form anyway, using TextInput is
    correct and solves the validation issue.

    The field is readonly in the template; its value is generated by frontend JS.
    """

    role = forms.ChoiceField(
        label='Rol',
        choices=[
            (UserCompany.RoleChoices.EMPLOYEE, 'Empleado'),
            (UserCompany.RoleChoices.MANAGER,  'Manager'),
        ],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False,
    )

    class Meta:
        model  = Users
        fields = ['username', 'surname', 'email', 'status', 'password']
        labels = {
            'username': 'Nombre',
            'surname':  'Apellidos',
            'email':    'Correo electrónico',
            'status':   'Estado',
            'password': 'Contraseña temporal',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'surname':  forms.TextInput(attrs={'class': 'form-control'}),
            'email':    forms.EmailInput(attrs={'class': 'form-control'}),
            'status':   forms.Select(attrs={'class': 'form-control'}),
            # TextInput instead of PasswordInput: prevents Django from dropping
            # the field value while processing POST.
            'password': forms.TextInput(attrs={
                'class':    'form-control font-monospace',
                'readonly': True,
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = False

    def save(self, commit=True):
        user     = super().save(commit=False)
        password = self.cleaned_data.get('password')
        if password:
            user.set_password(password)
        user.is_admin = False
        if commit:
            user.save()
        return user


# ── Auth ───────────────────────────────────────────────────────────────────────

class LoginForm(AuthenticationForm):
    username = forms.EmailField(
        label='Correo electrónico',
        widget=forms.EmailInput(attrs={
            'class':       'form-control',
            'placeholder': 'ejemplo@email.com',
        })
    )
    password = forms.CharField(
        label='Contraseña',
        widget=forms.PasswordInput(attrs={
            'class':       'form-control',
            'placeholder': '********',
        })
    )

    def clean_username(self):
        username = (self.cleaned_data.get('username') or '').strip()
        return username.upper()

# ── Login with company selection ────────────────────────────────────────────

class CompanySelectLoginForm(forms.Form):
    company_id = forms.ChoiceField(
        label='Selecciona empresa',
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    def __init__(self, *args, companies=None, **kwargs):
        super().__init__(*args, **kwargs)
        if companies:
            self.fields['company_id'].choices = [
                (str(m.company.id), m.company.name) for m in companies
            ]


# ── Company ───────────────────────────────────────────────────────────────────

class CompanyForm(forms.ModelForm):
    class Meta:
        model  = Companies
        fields = ['name', 'legal_name', 'tax_id']
        labels = {
            'name':       'Nombre de la empresa',
            'legal_name': 'Razón social',
            'tax_id':     'CIF / NIF',
        }
        widgets = {
            'name':       forms.TextInput(attrs={'class': 'form-control'}),
            'legal_name': forms.TextInput(attrs={'class': 'form-control'}),
            'tax_id':     forms.TextInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = False


# ── Worker ────────────────────────────────────────────────────────────────

class WorkerCreateForm(_UserBaseForm):
    """
    Create a new user.
    The temporary password (generated in the frontend) comes in 'password',
    is hashed with set_password(), and saved in users.password_hash.
    The view sets flag=False to force a password change on first login.
    """
    pass


class WorkerSelectForm(_UserBaseForm):
    """
    Edit an existing user found by email.
    The 'password' field is visual only: the view does NOT call
    set_password or modify flag for users that already exist in the DB.
    """
    pass


# ── First login: set final password ────────────────────────────

class SetPasswordForm(forms.Form):
    """
    Shown to users on their first login (flag=False).
    Requires setting a final password with complexity requirements.
    """
    new_password = forms.CharField(
        label='Nueva contraseña',
        widget=forms.PasswordInput(attrs={
            'class':        'form-control',
            'autocomplete': 'new-password',
            'placeholder':  'Mínimo 8 caracteres',
        }),
        min_length=8,
    )
    confirm_password = forms.CharField(
        label='Confirmar contraseña',
        widget=forms.PasswordInput(attrs={
            'class':        'form-control',
            'autocomplete': 'new-password',
        }),
    )

    def clean(self):
        cleaned_data     = super().clean()
        new_password     = cleaned_data.get('new_password', '')
        confirm_password = cleaned_data.get('confirm_password', '')

        if new_password != confirm_password:
            self.add_error('confirm_password', 'Las contraseñas no coinciden.')

        if new_password:
            has_upper = any(c.isupper() for c in new_password)
            has_lower = any(c.islower() for c in new_password)
            has_digit = any(c.isdigit() for c in new_password)
            special_chars = '!¡¿?@#$%^&*-_;:./~'
            has_special = any(c in special_chars for c in new_password)
            if not (has_upper and has_lower and has_digit and has_special):
                self.add_error(
                    'new_password',
                    'La contraseña debe contener mayúsculas, minúsculas, números y símbolos especiales (!¡¿?@#$%^&*-_;:./~).',
                )
        return cleaned_data


class ProfilePasswordChangeForm(forms.Form):
    """Password change form used in profile page with Spanish copy."""

    old_password = forms.CharField(
        label='Contraseña actual',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'autocomplete': 'current-password',
            'placeholder': 'Introduce tu contraseña actual',
        }),
        error_messages={
            'required': 'Debes introducir tu contraseña actual.',
        },
    )
    new_password = forms.CharField(
        label='Nueva contraseña',
        min_length=8,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'autocomplete': 'new-password',
            'placeholder': 'Mínimo 8 caracteres',
        }),
        help_text='Debe incluir mayúsculas, minúsculas, números y símbolos.',
        error_messages={
            'required': 'Debes introducir una nueva contraseña.',
            'min_length': 'La nueva contraseña debe tener al menos 8 caracteres.',
        },
    )
    confirm_password = forms.CharField(
        label='Confirmar nueva contraseña',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'autocomplete': 'new-password',
            'placeholder': 'Repite la nueva contraseña',
        }),
        error_messages={
            'required': 'Debes confirmar la nueva contraseña.',
        },
    )

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password', '')
        if not self.user.check_password(old_password):
            raise forms.ValidationError('La contraseña actual no es correcta.')
        return old_password

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password', '')
        confirm_password = cleaned_data.get('confirm_password', '')

        if new_password and confirm_password and new_password != confirm_password:
            self.add_error('confirm_password', 'Las contraseñas nuevas no coinciden.')

        if new_password:
            has_upper = any(c.isupper() for c in new_password)
            has_lower = any(c.islower() for c in new_password)
            has_digit = any(c.isdigit() for c in new_password)
            special_chars = '!¡¿?@#$%^&*-_;:./~'
            has_special = any(c in special_chars for c in new_password)

            if not (has_upper and has_lower and has_digit and has_special):
                self.add_error(
                    'new_password',
                    'La contraseña debe contener mayúsculas, minúsculas, números y símbolos especiales (!¡¿?@#$%^&*-_;:./~).',
                )

            if self.user.check_password(new_password):
                self.add_error(
                    'new_password',
                    'La nueva contraseña no puede ser igual a la actual.',
                )

        return cleaned_data

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password'])
        if commit:
            self.user.save(update_fields=['password'])
        return self.user