# Generated by Django 6.0.3 on 2026-04-29 09:57

import core.model_normalization
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_delete_companysettings_delete_correctionrequests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequests',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('new_clock_in', models.DateTimeField(blank=True, null=True)),
                ('new_clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('correction_note', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'correction_requests',
                'managed': False,
            },
            bases=(core.model_normalization.UppercaseNormalizationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('absence', 'Ausencia')], default='absence', max_length=20)),
                ('leave_reason', models.CharField(choices=[('annual', 'Vacaciones anuales'), ('sick', 'Baja por enfermedad'), ('maternity', 'Maternidad / Paternidad'), ('wedding', 'Matrimonio'), ('bereavement', 'Fallecimiento familiar'), ('medical_appointment', 'Cita médica'), ('legal_duty', 'Deber público / legal'), ('personal', 'Asuntos propios'), ('other', 'Otro')], default='other', max_length=30)),
                ('reason_note', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('attachment_path', models.CharField(blank=True, max_length=500, null=True)),
                ('attachment_verified', models.BooleanField(default=False)),
                ('force_proof', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='users.companies')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
