# Generated by Django 6.0.3 on 2026-03-18 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntries',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('confirmed', 'Confirmed'), ('auto_closed', 'Auto Closed'), ('corrected', 'Corrected'), ('voided', 'Voided')], default='ongoing', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEntryEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('clock_in', 'Clock In'), ('clock_out', 'Clock Out'), ('pause_start', 'Pause Start'), ('pause_end', 'Pause End'), ('manual_adjust', 'Manual Adjust'), ('reopen', 'Reopen'), ('auto_close', 'Auto Close')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_entry_event',
                'managed': False,
            },
        ),
    ]
