# Generated by Django 6.0.3 on 2026-05-15 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('generated', 'Generado'), ('signed', 'Firmado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('document_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'monthly_reports',
                'ordering': ['-report_date'],
                'managed': False,
            },
        ),
    ]
